# Generated by Django 5.2 on 2025-04-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved',
        ),
        migrations.AddField(
            model_name='request_product',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
