# Generated by Django 5.2 on 2025-04-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_remove_category_sub_category_sub_category_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_category', to='Website.category'),
            preserve_default=False,
        ),
    ]
