# Generated by Django 5.2 on 2025-04-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0011_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_product',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_product',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
