# Generated by Django 5.2 on 2025-04-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0012_request_product_email_request_product_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Created_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
