# Generated by Django 5.2 on 2025-04-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0014_request_product_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Created_users',
            new_name='Created_user',
        ),
        migrations.AlterField(
            model_name='request_product',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='request_product',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
