# Generated by Django 5.2 on 2025-06-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0016_delete_created_user_category_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
    ]
