# Generated by Django 5.2 on 2025-06-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0017_alter_sub_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
