# Generated by Django 5.2 on 2025-04-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_model', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
