# Generated by Django 5.2 on 2025-04-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_model', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
